FROM node:latest AS builder

WORKDIR /usr/src/api

COPY . .
RUN npm install && npm run build


FROM nginx:latest

RUN rm -r -f /usr/share/nginx/html
COPY --from=builder /usr/src/api/build /usr/share/nginx/html
