services:
  backend:
    container_name: backend
    build:
      context: "./"
      dockerfile: "./api/dockerfile.dev"
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    working_dir: /src
    # command: sh -c "poetry run python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn main:app --reload --proxy-headers --host='0.0.0.0' --port=8000"
    # command: sh -c "poetry run uvicorn api.main:app --host 0.0.0.0 --reload"
    ports:
      - 8000:8000
      - 5678:5678
    tty: true
    stdin_open: true

  db:
    container_name: db
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'db_for_app'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306

volumes:
  mysql_data:
