version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.demo
    command: yarn start
    volumes:
      - ./frontend:/usr/src/api
    ports:
      - "3000:3000"

  demo-app:
    tty: true
    build:
      context: ./api
      dockerfile: "dockerfile.demo"
    volumes:
      - .dockervenv:/usr/src/.venv
      - .:/usr/src
    ports:
      - 8000:8000
      
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'db_for_app'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
volumes:
  mysql_data:
