FROM python:3.12
ENV PYTHONUNBUFFERED=1

WORKDIR /src

RUN pip install poetry
RUN git clone https://github.com/Hashobrin/meishi.git
RUN ssh-keygen -t rsa -f key4github

COPY pyproject.toml* poetry.lock* ./

RUN poetry config virtualenvs.in-project true
RUN if [ -f pyproject.toml ]; then poetry install --no-root; fi

ENTRYPOINT ["poetry", "run", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--reload"]
